### ISSUE TITLE
CBreadcrumbRouter and CSidebarNav not supporting route parameters

### ISSUE THREAD

**Issue by de1mat** [coreui/coreui-react#118] opened 2020-06-02 21:43 UTC
I have the following example routes:

```
{ path: '/websites', name: 'Websites', component: Websites, exact: true },
{ path: '/websites/:websiteId', name: 'Website', component: EditWebsite, exact: true },
```

If I go to `/websites` then the breadcrumb shows "Home > Websites" which is correct. And the Sidebar correctly highlights "Websites" in the list.

If I go to `/websites/12345` then the breadcrumb still shows "Home > Websites". It should show "Home > Websites > Website". And the Sidebar is no longer highlighting "Websites" even though I am in a subroute of `/websites` still.

Both these scenarios worked perfectly in CoreUI 2.0.

Is there something I need to change? Or do these newer components not support route parameters yet?

**Comment by wilburluce** [comment] 2020-06-17 03:26
I hit this issue too. It was fixed in 2.0 https://github.com/coreui/coreui-free-react-admin-template/issues/27 - somehow this has regressed

**Comment by wilburluce** [comment] 2020-06-17 04:37
Using free version of template, npm list @coreui/react is 3.0.2  - here's commit that fixed the issue in v2.x  https://github.com/coreui/coreui-react/commit/969bd9c8d5b8c088ad847e0a09b0af7a931c67e0 @woothu are you able to take a look at this for us? thank you in advance, if not ill try to come up with a PR

**Comment by woothu** [comment] 2020-06-17 09:27
Hi, thank you for this report!

- CBreadcrumbRouter will receive the fix in incoming version, (6d8b59b)
- CSidebarNavDropdown has 'route' prop which specifies the prefix for all the items that are inside dropdown, so it shouldn't rely on parameters

**Closed by woothu** 2020-06-17 09:27 UTC

**Comment by woothu** [comment] 2020-06-17 12:12
Fix released in 3.0.3 version

**Comment by de1mat** [comment] 2020-06-17 13:24
Thanks for the fix I will try it tomorrow.

Regarding the Sidebar - I am not using nested Dropdowns. And I don't think the issue was quite understood. The issue is that it is no longer highlighting "Websites" even though I am in a subroute of /websites still. If I move into pages inside the /websites route, no mater how deep, the top level nav item should stay selected. It does not at the moment. Maybe you mean I need to tweak my SideNav code slightly to resolve this? I will check this tomorrow as well just in case I missed something.

**Comment by woothu** [comment] 2020-06-17 13:40
It should stay open if you have set `route` prop in `CSidebarNavDropdown` to '/websites'

**Comment by wilburluce** [comment] 2020-06-18 00:00
I tried the fix in 3.0.3 and it didnt work for me. When navigating via a link to the route with an id, the breadcumb didnt present the :id as crumb name, it duplicated the previous name in list, so it was like Home > Model > Model vs the expected Home > Model > 123456  .. i havent had time to dig into futher.. but will spend more time soon

**Comment by woothu** [comment] 2020-06-18 08:14
@willbruce Breadcrumb shows route name, not a current parameter, it is intended behavior.

In this case, you can take the CBreadcrumbRouter code and customize it for your case.

**Comment by wilburluce** [comment] 2020-06-18 21:05
@woothu - ok understood regarding the intended behavior. I do think i found a small bug on the fix in 3.0.3 - the current link is styled as clickable (blue).. when clicked it changes to grey
![image](https://user-images.githubusercontent.com/1524961/85071666-b507e800-b16c-11ea-9337-a03e53c15aeb.png)

**Comment by de1mat** [comment] 2020-06-21 20:39
There are still issues in 3.0.3 for me.

Going back to the original bug report. I have the following routes:

```
{ path: '/websites', name: 'Websites', component: Websites, exact: true },
{ path: '/websites/:websiteId', name: 'Website', component: EditWebsite, exact: true },
```

## The Breadcrumb Issues in 3.0.3

If I go to `/websites` then the breadcrumb shows "Home > Websites" which is correct. 

If I go to `/websites/12345` then the breadcrumb now correctly shows "Home > Websites > Website". But...

1. The last item "Website" is in bold and is linked. i.e. it is not being detected as "active".
2. The link for "Website" is showing as `<a href="/websites/:websiteId">Website</a>`.

## The Sidebar Issue

So I do not use `CSidebarNavDropdown`. I just have the top-level "modules" linked to in the side menu as shown in the pic below. 

![image](https://user-images.githubusercontent.com/901045/85234689-458f4280-b463-11ea-9b6d-8363c31ef4c8.png)

If I go to `/websites` then the Sidebar correctly highlights "Websites" as shown in the above screenshot ✅

If I go to `/websites/12345` then "Websites" is no longer selected, as shown in the screenshot below ❌ But I would expect this to remain selected, as it did in CoreUI v2.

![image](https://user-images.githubusercontent.com/901045/85234713-7c655880-b463-11ea-8876-db3ff9949feb.png)

Adding `route` to the `CSidebarNavItem` does not seem to make any difference and maybe is not supported for that component but should be.

**Comment by woothu** [comment] 2020-06-23 07:12
Thank you for the report!

Regarding CBreacrumbRouter it was fixed again in 3.0.4 version (Now the real path is referenced instead of router route 7e2c87b)

CSidebarNavItem: 
Unlike CLink it is set to `exact=true` by default, it prevents multiple sidebar items to be displayed as active simultaneously.
Set `exact=false` to disable this behavior.

**Comment by de1mat** [comment] 2020-06-23 20:38
@woothu thank you! Version `3.0.4` is working perfectly 👍

**Comment by benplain** [comment] 2020-06-24 23:47
@woothu, Is there any chance this could be fixed in coreui-vue as well? Should I raise the same issue over there?

**Comment by woothu** [comment] 2020-06-25 07:58
@benplain not necessary, We have it on our TODO list for the next release

**Comment by jivansupe** [comment] 2021-11-08 10:59
I have a question regarding the BreadCrumbs. My scenario is: 

```
{ path: '/data/:id', exact: true, name: 'Data', component: Data},
{ path: '/data/data-edit/:id', exact: true, name: 'Data Edit', component: DataEdit}
```

1st path line BreadCrumbs is:    **Data**
   and URL becomes **http://localhost:3000/#/data/1634892060**
2st path line BreadCrumbs is:    ** _Data_ > Data Edit**
   and URL becomes   **http://localhost:3000/#/data/data-edit/1634892060**

When I click on "_Data_" from the 2nd mentioned path, it redirects to **http://localhost:3000/#/data/data-edit** without the id (1634892060). 
Am I missing something or doing it in the wrong way? Or is it a bug? Not able to understand it. 

thanks.

**Comment by de1mat** [comment] 2021-11-09 17:32
> When I click on "_Data_" from the 2nd mentioned path, it redirects to **http://localhost:3000/#/data/data-edit** without the id (1634892060). Am I missing something or doing it in the wrong way? Or is it a bug? Not able to understand it.

The breadcrumb just generates plain HTML with text and links. If the generated link is correct (which it looks ok) then its job is done and it is working fine. Any redirect that happens is more likely related to the page component being loaded or some other routing issue, not to the breadcrumb component.
