### ISSUE TITLE
Smart table not rerender on items changed

### ISSUE THREAD

**Issue by simbik** [coreui/coreui-react#220] opened 2021-11-02 17:32 UTC
Hello, i try to use SmartTable, but it not changing when i take items from backend.

My call is 
```
<CSmartTable
        loading={loading}
        tableProps={{
          hover: true,
        }}
        items={items}
        columns={fields}
        cleaner
        noItemsLabel="Данные не найдены"
        itemsPerPageLabel="Записей на странице:"
        itemsPerPage={itemsPerPage}
        onItemsPerPageChange={setItemsPerPage}
        itemsPerPageSelect
        pagination={false}
        itemsPerPageOptions={[2, 3, 4, 5, 6]}
        scopedColumns={scopedSlots}
      />
```

Items changing, but table no.

**Comment by mrholek** [comment] 2021-11-03 12:04
Whether the variable `items` is reactive

**Comment by simbik** [comment] 2021-11-03 12:15
Yes, of corse.
const [items, setItems] = useState([]);

**Comment by mrholek** [comment] 2021-11-03 12:37
Can you try one more thing? Please set page number one and then try to update items?

**Comment by TheDemeaN** [comment] 2021-11-04 17:03
I'm having the exact same problem as @simbik

**Comment by mrholek** [comment] 2021-11-05 18:50
@simbik @TheDemeaN I fixed it. I will try to publish a new version this weekend.

**Comment by mrholek** [comment] 2021-11-08 11:25
Fixed in v4.0.1

**Closed by mrholek** 2021-11-08 11:25 UTC

**Comment by Getterac7** [comment] 2022-01-12 20:22
I'm having this same issue with CSmartTable not rerendering when updating items. Using @coreui/react-pro v4.1.1 and v4.1.3.

```jsx
const [itemList, setItemList] = useState([])

<CSmartTable
items={itemList}
columns={tableFields}
pagination
tableFilter
tableProps={{
  hover: true,
  striped: true,
}}
selectable
columnSorter
onSelectedItemsChange={setSelected}
/>
```

**Comment by mrholek** [comment] 2022-01-13 00:00
@Getterac7 can you show me how you update items?

**Comment by Getterac7** [comment] 2022-01-13 01:48
> @Getterac7 can you show me how you update items?

```ts
  const downloadItems = useCallback(() => {
    Api.getItems().then((data) => {
      setItemList(data)
    })
  }, [Api])

  useEffect(() => {
    downloadItems()
  }, [downloadItems])
```

This format worked great for CoreUI v3 CDataTable. Nothing changed except swapping out CDataTable for CSmartTable.

**Comment by mrholek** [comment] 2022-01-13 13:15
@Getterac7 I just tried following example and everything works

```
const [users, setUsers] = useState([])
const downloadUsers = useCallback(() => {
  const result = fetch('https://jsonplaceholder.typicode.com/users')
  .then((response) => response.json())
  .then((result) => {
    setUsers(result)
  })
}, [])
useEffect(() => {
  downloadUsers()
}, [downloadUsers])
return (
  <CSmartTable
    items={users}
    columnFilter
    columnSorter
    pagination
    tableProps={{
      hover: true,
      responsive: true,
    }}
  />
)
```

**Comment by mrholek** [comment] 2022-01-13 13:16
@Getterac7 please check if you have @coreui/react-pro@4.1.3

**Comment by Getterac7** [comment] 2022-01-13 15:06
I have a reproducible example here. Looks like <React.StrictMode> is causing the issue. Works fine without it.
https://codesandbox.io/s/romantic-bose-169id

**Comment by mrholek** [comment] 2022-01-16 21:35
@Getterac7 I will try to fix it next week.
